### ISSUE TITLE
Doesnt work here...

### ISSUE THREAD

**Issue by AlexVKO** [fnando/signal#1]
Hi Nando Vieira, very nice syntax, i saw your lecture on RubyConf, congratulations, was Awesome.

Well, I do not know if I'm doing something wrong, this code should work?

```ruby
class Api::V1::ContactsController < ApplicationController
  # POST
  def create
    contact = Contact.create(contact_params)
      .on(:success) { head 201 }
      .on(:failure) { render json: { errors: contact.errors }, status: 422 }
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end
```

It raise Missing template... i only includes the library in my model, should i do anything else?

Thank you.

**Comment by fnando** [comment]
Which module did you include? Make sure you're including `Signal::ActiveRecord`. And in case of ActiveRecord objects you should be listening to `:create` and `:validation` events.

**Comment by AlexVKO** [comment]
Thank you, for the quick reply.

```ruby
#controller
class Api::V1::ContactsController < ApplicationController

  # POST
  def create
    contact = Contact.create(contact_params) #when i use method new here
      .on(:create) { head 201 }
      .on(:validation) { render json: { errors: contact.errors }, status: 422 }

  # and call contact.save here, it works but not properly...
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end
```

``` ruby
#model
class Contact < ActiveRecord::Base
  include Signal::ActiveRecord
  validates_presence_of :name, :email, :message, :subject
end
```


Still raise ActionView::MissingTemplate
running rails 4.2.3 and ruby 2.2.2.

Im trying to refactor this:

```ruby
class Api::V1::ContactsController < ApplicationController

  # POST
  def create
    contact = Contact.create(contact_params)
    if contact.save
      head 201
    else
      render json: { errors: contact.errors }, status: 422
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end
```

**Comment by fnando** [comment]
Sorry... I think I was too tired yesterday. The problem is that you're calling `Contact.create`; so this will save/validate your record _before_ you bind the events. So that's why you're never triggering the events.

Easy solution, use something like this:

```ruby
Contact.new(contact_params)
  .on(:create) { head 201 }
  .on(:validation) {|contact| render json: contact.errors, status: 422 } 
  .save
```

See? I'm attaching the events first, then trying to save the record.

**Comment by AlexVKO** [comment]
Awesome!
It works perfectly. Thank you very much!

For this case, do you think `on(:validation)` better than `on(:failure)` ? or did you changed it for a reason?
I think is more readable `on(:failure)`. If you agree, i can make the changes... i'm not experienced but i can try.

:.
