### ISSUE TITLE
uninitialized constant Signal::ActiveRecord::Base

### ISSUE THREAD

**Issue by ricardopacheco** [fnando/signal#2]
```ruby
class SystemSubscribe::AddSubscriber
  include Signal
  attr_accessor :subscribe

  def initialize options={}
    @subscribe = Subscriber.new(options)
  end

  def call
    ActiveRecord::Base.transaction do
      return emit(:failure) unless save_subscribe
      send_subscriber_email
    end

    emit(:success, @subscribe)
  end

  private
  def save_subscribe
    @subscribe.save
  end

  def send_subscriber_email
    SubscriberNotifier.add_subscriber(@subscribe).deliver
  end
end
```

**Comment by fnando** [comment]
Can you paste the full backtrace?

**Comment by ricardopacheco** [comment]
NameError: uninitialized constant Signal::ActiveRecord::Base
  from /Users/ricardopacheco/projects/socialcrm/app/services/system_subscribe/add_subscriber.rb:10:in `call'
  from (irb):10
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from /Users/ricardopacheco/projects/socialcrm/bin/rails:8:in `<top (required)>'
  from /Users/ricardopacheco/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/ricardopacheco/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from -e:1:in `<main>'

**Comment by fnando** [comment]
The problem is that the AR extensions does use the same module name (`ActiveRecord`). An alternative would be using something like `include Signal.active_record`, and delegate this to a different module.

Now, to solve your problem, for now, you can use `::ActiveRecord::Base.transaction`.

**Comment by fnando** [comment]
Just released v1.0.0, so you have to use `include Signal.active_record` now.

**Comment by ricardopacheco** [comment]
@fnando I did what indicated to me and occurred another error:

NoMethodError: undefined method `around_create' for SystemSubscribe::AddSubscriber:Class
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/signal-1.0.0/lib/signal/extensions/active_record.rb:12:in `block in included'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/signal-1.0.0/lib/signal/extensions/active_record.rb:9:in `class_eval'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/signal-1.0.0/lib/signal/extensions/active_record.rb:9:in `included'
  from /Users/ricardopacheco/projects/socialcrm/app/services/system_subscribe/add_subscriber.rb:2:in `include'
  from /Users/ricardopacheco/projects/socialcrm/app/services/system_subscribe/add_subscriber.rb:2:in `<class:AddSubscriber>'
  from /Users/ricardopacheco/projects/socialcrm/app/services/system_subscribe/add_subscriber.rb:1:in `<top (required)>'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:354:in `require_or_load'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'
  from (irb):4
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
  from /Users/ricardopacheco/projects/socialcrm/bin/rails:8:in `<top (required)>'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/ricardopacheco/.rvm/gems/ruby-2.2.3@socialcrm/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
  from /Users/ricardopacheco/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/ricardopacheco/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by fnando** [comment]
You included `Signal.active_record`? That should be done only for AR models (which is not your case). Just use regular `include Signal` on PORO classes.

**Comment by ricardopacheco** [comment]
Yes! This error has happened before when I called Signal::ActiveRecord in 0.3.0 version

**Comment by fnando** [comment]
Let's start over, this time in pt-BR.

Pelo que vejo, o erro em `SystemSubscribe::AddSubscriber` acontece porque você está adicionando `include Signal.active_record`.

Na verdade, o seu código deve exatamente igual ao primeiro comentário da thread. 

```ruby
class SystemSubscribe::AddSubscriber
  include Signal
  attr_accessor :subscribe

  def initialize options={}
    @subscribe = Subscriber.new(options)
  end

  def call
    ActiveRecord::Base.transaction do
      return emit(:failure) unless save_subscribe
      send_subscriber_email
    end

    emit(:success, @subscribe)
  end

  private
  def save_subscribe
    @subscribe.save
  end

  def send_subscriber_email
    SubscriberNotifier.add_subscriber(@subscribe).deliver
  end
end
```

**Comment by ricardopacheco** [comment]
É isso mesmo @fnando, muito obrigado! :+1:
