### ISSUE TITLE
pt-BR: Trabalhando com formatos no controller

### ISSUE THREAD

**Issue by ricardopacheco** [fnando/signal#3]
Foi colocado um exemplo de como usar signal no controller:
```ruby
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)

    Signup.new(@user)
      .on(:success) { redirect_to login_path, notice: 'Welcome to MyApp!' }
      .on(:failure) { render :new }
      .call
  end
end
```

No caso você está tratando considerando o format como html. E Quando você precisa lidar com 3 casos por exemplo? (html, js e JSON). Eu devo passar outro bloco dentro?

```ruby
.on(:success) { 
  respond_to do |format|
    format.html { redirect_to ... }
    format.json { render ... }
    format.js 
  end
}
.on(:failure) { 
  respond_to do |format|
    format.html { render :new }
    format.json { render ... }
    format.js 
  end
}
```

Ou seja, para cada emit, eu duplicaria os tipos de responder. Como eu posso contornar isso?

**Comment by fnando** [comment]
Não costumo usar `respond_to` (normalmente crio endpoints diferentes para uma API JSON e tal. Mas o seu último exemplo parece bem fácil de ler, na minha opinião.
