### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by sobrinho** [fnando/signal#5]
Would be nice to have some kind of native i18n support, like:

``` ruby
class SomeWork
  include Signal
  include Signal::I18n

  def call
    if failure?
      emit(:failure)
    else
      emit(:success)
    end
  end
end
```

And that mapping to something like `emit(:success, I18n.t(:success, scope: :'signal.some_work'))`.

Too specific?

**Comment by fnando** [comment]
I don't know… does it make sense emitting a string for _every_ event? I don't think so.

Maybe you should create some helpers for what you're trying to do. Something like `emit_with_message(event)`, which infers the class name and finds the appropriate scope.

**Comment by sobrinho** [comment]
Thinking better I don't believe this fits to the signal core itself, we ended creating a small object for the application which seems to makes more sense:

``` ruby
module MyApplication
  class Action
    include Signal

    private

    def t(key, *args)
      options = args.extract_options!
      options[:scope] = i18n_scope

      I18n.t(key, *args << options)
    end

    def i18n_scope
      [:signal, self.class.name.underscore]
    end
  end
end
```

That way we are using like this:

``` ruby
def call
  emit(:success, t(:success))
end
```

I'm going to create a wiki page about that, depending (even indirectly) on i18n seems odd, thanks.

**Comment by sobrinho** [comment]
There is no wiki enabled :sob:
